apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-service
  namespace: rideshare
spec:
  selector:
    matchLabels:
      app: rider-service
  template:
    metadata:
      labels:
        app: rider-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: rider-service
                topologyKey: topology.kubernetes.io/zone
      initContainers:
        - name: rider-migrate
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: rider-service-config
            - secretRef:
                name: rider-service-credentials
          command: ["node", "dist/migrations/createTable.js"]

      containers:
        - name: rider-service
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: rider-service-config
            - secretRef:
                name: rider-service-credentials
          resources:
            requests:
              cpu: 75m
              memory: 150Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /api/v1/riders/health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/riders/health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 20
