apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rider-service-credentials
  namespace: rideshare
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: rider-service-credentials
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: ENV_PREFIX-app/data-urls
        property: DATABASE_URL

    - secretKey: JWT_SECRET
      remoteRef:
        key: ENV_PREFIX/jwt
        property: JWT_SECRET

    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: ENV_PREFIX/rider-oauth
        property: GOOGLE_CLIENT_ID

    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: ENV_PREFIX/rider-oauth
        property: GOOGLE_CLIENT_SECRET

    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: ENV_PREFIX-redis/redis
        property: REDIS_PASSWORD

    - secretKey: REDIS_HOST
      remoteRef:
        key: ENV_PREFIX-redis/redis
        property: REDIS_HOST
