name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# GRANT GLOBAL PERMISSIONS SO THE REUSABLE WORKFLOW CAN INHERIT THEM
permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  pipeline:
    uses: khadree/devops-platform-ci/.github/workflows/ci.yml@main
    with:
      service-name: kadiri-rider-service # ECR repo name
      eks-deployment-name: rider-service   # Kubernetes deployment name
      language: "javascript"                      # Language for codeql scanning
      trivy-severity: "CRITICAL,HIGH"
     # deploy: true 
    secrets: inherit                         # Passes all repo secrets automatically